import { ObjectID } from "mongodb";

export default interface Character {
  user: string,
  _id: ObjectID,
  basics: {
    name: String,
    player: String,
    LVL: String,
    XP: String,
    homeland: String,
    type: String,
    alignment: String,
    deity: String,
    abilityBoost: String
  },
  appearance: {
    age: string,
    eyes: string,
    hair: string,
    weight: string,
    height: string,
    gender: string,
  },
  mainStats: {
    STR: string,
    DEX: string,
    CON: string,
    INT: string,
    WIS: string,
    CHA: string,
    AC: string,
    TOUCHAC: string,
    HP: string,
  },
  modifiers: {
    CHA: string,
    CON: string,
    DEX: string,
    INT: string,
    WIS: string,
    STR: string,
    FORT: string,
    REFLEX: string,
    TOUCHAC: string,
    AC: string,
    PER: string,
  },
  items: {
    worn: string,
    ready: string,
    stowed: string,
    coins: {
      platinum: number,
      gold: number,
      silver: number,
      copper: number,
    },
    bulk: string,
  },
  ancestryProps: {
    ancestry: string,
    size: string,
    speed: number,
    languages: string,
    ancestryTraits: string[],
    attributes: object
  },
  backgroundProps: {
    background: string,
    selectBoost: string[],
    freeAbilityBoost: number,
    skillFeat: string,
    loreSkill: string,
  },
  classProps: {
    class: string,
    keyAbility: string[],
    proficiencies: object,
    savingThrows: object,
    skills: object,
    weapons: object,
    armor: object,
    signatureSkills: string[],
    classFeatures: string[],
    items: object,
  },
  characterTraits: object,
  characterNotes: string,
  skillsModifiers: object,
  skillFeats: string,
  spells: object,
  actions: {
    string: string,
    melee: string[],
    ranged: string[],
  },
  feats: object,
  created: Date
}