import { ObjectID } from "mongodb"
import { Document, model, Model, Schema } from 'mongoose'

const CharacterSchema: Schema = new Schema({
  _id: ObjectID,
  user: String,
  basics: {
    name: String,
    player: String,
    LVL: String || Number,
    XP: String,
    homeland: String,
    type: String,
    alignment: String,
    deity: String,
    abilityBoost: String,
  },
  appearance: {
    age: String,
    eyes: String,
    hair: String,
    weight: String,
    height: String,
    gender: String,
  },
  mainStats: {
    STR: String,
    DEX: String,
    CON: String,
    INT: String,
    WIS: String,
    CHA: String,
    AC: String,
    TOUCHAC: String,
    HP: String,
  },
  modifiers: {
    CHA: String,
    CON: String,
    DEX: String,
    INT: String,
    WIS: String,
    STR: String,
    FORT: String,
    WILL: String,
    REFLEX: String,
    TOUCHAC: String,
    AC: String,
    PER: String,
  },
  items: {
    worn: String,
    ready: String,
    stowed: String,
    coins: {
      platinum: Number,
      gold: Number,
      silver: Number,
      copper: Number,
    },
    bulk: String,
  },
  ancestryProps: {
    ancestry: String,
    size: String,
    speed: Number,
    languages: String,
    ancestryTraits: Array,
    attributes: Object
  },
  backgroundProps: {
    background: String,
    selectBoost: Array,
    freeAbilityBoost: Number,
    skillFeat: String,
    loreSkill: String,
  },
  classProps: {
    class: String,
    keyAbility: Array,
    proficiencies: Object,
    savingThrows: Object,
    skills: Object,
    weapons: Object,
    armor: Object,
    signatureSkills: Array,
    classFeatures: Array,
    items: Array,
  },
  characterTraits: Object,
  characterNotes: String,
  skillsModifiers: Object,
  skillFeats: String,
  spells: Object,
  actions: {
    stride: String,
    melee: Array,
    ranged: Array,
  },
  feats: Object,
})

interface ICharacterDoc extends Document {
  user: string,
  _id: ObjectID,
  basics: {
    name: string,
    player: string,
    LVL: string | number,
    XP: string,
    homeland: string,
    type: string,
    alignment: string,
    deity: string,
    abilityBoost: string
  },
  appearance: {
    age: string,
    eyes: string,
    hair: string,
    weight: string,
    height: string,
    gender: string,
  },
  mainStats: {
    STR: string,
    DEX: string,
    CON: string,
    INT: string,
    WIS: string,
    CHA: string,
    AC: string,
    TOUCHAC: string,
    HP: string,
  },
  modifiers: {
    CHA: string,
    CON: string,
    DEX: string,
    INT: string,
    WIS: string,
    STR: string,
    FORT: string,
    WILL: string,
    REFLEX: string,
    TOUCHAC: string,
    AC: string,
    PER: string,
  },
  items: {
    worn: string,
    ready: string,
    stowed: string,
    coins: {
      platinum: number,
      gold: number,
      silver: number,
      copper: number,
    },
    bulk: string,
  },
  ancestryProps: {
    ancestry: string,
    size: string,
    speed: number,
    languages: string,
    ancestryTraits: string[],
    attributes: object
  },
  backgroundProps: {
    background: string,
    selectBoost: string[],
    freeAbilityBoost: number,
    skillFeat: string,
    loreSkill: string,
  },
  classProps: {
    class: string,
    keyAbility: string[],
    proficiencies: object,
    savingThrows: object,
    skills: object,
    weapons: object,
    armor: object,
    signatureSkills: string[],
    classFeatures: string[],
    items: string[],
  },
  characterTraits: object,
  characterNotes: string,
  skillsModifiers: object,
  skillFeats: string,
  spells: object,
  actions: {
    stride: string,
    melee: string[],
    ranged: string[],
  },
  feats: object,
  created: Date
}

export const CharacterModel: Model<ICharacterDoc> = model<ICharacterDoc>('characters', CharacterSchema)
